security:
    providers:
        users:
            entity: { class: AiconoaUserBundle:User, property: username }

    encoders:
        Aiconoa\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/create, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
